name: CI/CD Pipeline

on:
 pull_request:
   types: [opened, synchronize, reopened]

jobs:

 test-and-build:
   runs-on: ubuntu-latest
   steps:
   
     - name: set up JDK 17
       uses: actions/setup-java@v1
       with:
          java-version: 17
   
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Run unit tests
       run: ./gradlew testDebugUnitTest

     - name: Upload test results
       uses: actions/upload-artifact@v2
       with:
         name: test-results
         path: app/build/reports/tests/testDebugUnitTest/
         
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Build APK
       run: ./gradlew assembleDebug

     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
         name: app-debug
         path: app/build/outputs/apk/debug/app-debug.apk
