name: CI/CD Pipeline

on:
 push:
   branches: [ develop ]

jobs:

 test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Run unit tests
       run: ./gradlew testDebugUnitTest

     - name: Upload test results
       uses: actions/upload-artifact@v2
       with:
         name: test-results
         path: app/build/reports/tests/testDebugUnitTest/

 build-apk:
   needs: test
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Build APK
       run: ./gradlew assembleDebug

     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
         name: app-debug
         path: app/build/outputs/apk/debug/app-debug.apk
